# Generated by Django 2.1.4 on 2019-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190409_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
    ]
