# Generated by Django 2.1.5 on 2019-04-19 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20190409_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='change_user',
        ),
        migrations.AddField(
            model_name='changes',
            name='change_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
