# Generated by Django 2.1.5 on 2019-04-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190419_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
