# Generated by Django 2.1.4 on 2019-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190612_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
